meta-sdk: Mask the unneeded recipes-security bbs
Issue: LIN1022-3147

We don't need the bb or bbappend under the recipes-security directory in
meta-sdk, and they may cause the following error due to the dangling
bbappend. So mask them.
  ERROR: No recipes in default available for:
  /home/wrlbuild/builds/builds-d3f45924-c1a1-49dc-bcbe-df6a5180610c/layers/meta-imx/meta-sdk/recipes-security/stmm-imx/optee-os_3.%.imx.bbappend

(LOCAL REV: NOT UPSTREAM) - WRLinux specific

Signed-off-by: Kevin Hao <kexin.hao@windriver.com>