imx-gpu-apitrace_10.0.0.bb: Require imx-gpu-apitrace_10.0.0.bb from meta-freescale layer specifically
Issue: LIN1022-4494

Workaround for meta-imx/meta-bsp'
require recipes-graphics/imx-gpu-apitrace/imx-gpu-apitrace_10.0.0.bb,
otherwise, there would be parsing errors when meta-freescale is behind
of meta-imx in conf/bblayers.conf:

RecursionError: maximum recursion depth exceeded while calling a Python object

Define LAYER_PATH_freescale-layer, then meta-imx/meta-bsp can use the following
to fix the error:
require ${LAYER_PATH_freescale-layer}/recipes-graphics/imx-gpu-apitrace/imx-gpu-apitrace_10.0.0.bb

The layerindex can 100% reproduce the error.

(LOCAL REV: NOT UPSTREAM) - Will send to upstream later

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>